--- #YAML:1.0
name:               MooseX-Documenter
version:            0.01
abstract:           class for getting Moose documentation for your Moose classes
author:
    - David Bury <dsbike@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:                0
    PPI::Document:        0
    Test::Exception:      0
    Test::MockObject::Extends:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
